FROM mcr.microsoft.com/dotnet/core/sdk:3.1-bionic AS build-env

# Runtime dependencies
RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
    # OpenCV dependencies
        libavutil-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libgtk2.0-0 libopenexr22 libtesseract-dev libdc1394-22-dev \
     && rm -rf /var/lib/apt/lists/*